version: '3'

services:
  api:
    restart: always
    env_file:
      - .env
    build: .
    command: >
      sh -c "python3 manage.py migrate &&
             python manage.py collectstatic --no-input &&
             python3 manage.py runserver 0.0.0.0:8030
             "
    ports:
      - "8030:8030"
    container_name: backend