# Generated by Django 5.0.3 on 2024-05-11 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_cart_discounts_discountscart_order_productunit_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productunit",
            options={
                "verbose_name": "ЕДИНИЦА ТОВАРА",
                "verbose_name_plural": "ЕДИНИЦЫ ТОВАРОВ",
            },
        ),
        migrations.AlterUniqueTogether(
            name="productunit",
            unique_together={("product", "size", "price")},
        ),
        migrations.AddField(
            model_name="productunitscart",
            name="count",
            field=models.IntegerField(
                default=0,
                help_text="Количество единиц товара в корзине",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Количество",
            ),
        ),
        migrations.AlterField(
            model_name="productunit",
            name="price",
            field=models.CharField(
                help_text="Цена товара в рублях",
                max_length=128,
                validators=[django.core.validators.DecimalValidator],
                verbose_name="Цена",
            ),
        ),
        migrations.RemoveField(
            model_name="productunit",
            name="reserved",
        ),
        migrations.RemoveField(
            model_name="productunit",
            name="title",
        ),
    ]
