# Generated by Django 5.0.3 on 2024-05-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_productunit_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productunit",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Цена товара в рублях",
                max_digits=10,
                max_length=128,
                verbose_name="Цена",
            ),
        ),
    ]
