# Generated by Django 5.0.3 on 2024-05-11 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_productunit_title_alter_productunit_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productunit",
            name="title",
        ),
    ]
