# Generated by Django 5.0.3 on 2024-05-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_remove_productunit_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discountscart",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="discountscart",
            name="cart",
        ),
        migrations.AlterField(
            model_name="cart",
            name="uuid",
            field=models.UUIDField(auto_created=True),
        ),
        migrations.DeleteModel(
            name="Discounts",
        ),
        migrations.DeleteModel(
            name="DiscountsCart",
        ),
    ]
