# Generated by Django 5.0.3 on 2024-05-11 21:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_cart_options_order_status_alter_cart_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="order",
            name="confirmed",
        ),
        migrations.AlterField(
            model_name="cart",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("6b2b2cbe-3598-491a-9b9c-c7a715de54fe"),
                editable=False,
                verbose_name="Идентификатор пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="productunit",
            name="size",
            field=models.ForeignKey(
                help_text="Размер единицы товара",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_units",
                to="shop.size",
                verbose_name="Размер",
            ),
        ),
    ]
