# Generated by Django 5.0.3 on 2024-05-11 21:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_remove_order_completed_remove_order_confirmed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("8c7b3851-38c0-493a-9997-d529c4387594"),
                editable=False,
                verbose_name="Идентификатор пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "создан"),
                    (1, "подтвержден"),
                    (2, "выполнен"),
                    (3, "отменен"),
                    (4, "возвращен"),
                ],
                default=0,
                help_text="Статус заказа",
                verbose_name="Статус",
            ),
        ),
    ]
