# Generated by Django 5.0.3 on 2024-05-11 21:12

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_alter_cart_uuid_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("b7f4b58d-1e89-44b4-a323-aa1dcda860e3"),
                editable=False,
                verbose_name="Идентификатор пользователя",
            ),
        ),
    ]
