# Generated by Django 5.0.3 on 2024-05-11 21:47

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_alter_cart_created_at_alter_cart_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("9120e447-0761-4ec8-8fb7-0287ffd48529"),
                editable=False,
                verbose_name="Идентификатор пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("создан", "создан"),
                    ("подтвержден", "подтвержден"),
                    ("выполнен", "выполнен"),
                    ("отменен", "отменен"),
                    ("возвращен", "возвращен"),
                ],
                default="создан",
                help_text="Статус заказа",
                verbose_name="Статус",
            ),
        ),
    ]
