# Generated by Django 5.0.3 on 2024-05-12 16:37

import uuid

import django.core.validators
import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_alter_cart_uuid_alter_order_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={
                "verbose_name": "Корзина покупателя",
                "verbose_name_plural": "Корзины покупателей",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "verbose_name": "ЗАКАЗ ПОКУПАТЕЛЯ",
                "verbose_name_plural": "ЗАКАЗЫ ПОКУПАТЕЛЕЙ",
            },
        ),
        migrations.AlterField(
            model_name="cart",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("eb6eaa89-47ba-4fb2-af23-f27446286d80"),
                editable=False,
                verbose_name="Идентификатор пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="shop.cart",
                verbose_name="Корзина",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=8,
                max_length=8,
                prefix="",
                verbose_name="Идентификатор заказа",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Электронная почта заказчика"),
        ),
        migrations.AlterField(
            model_name="order",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Имя заказчика"),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_phone",
                        message="Неверный формат",
                        regex="^[+]7[0-9]{7,14}$",
                    )
                ],
                verbose_name="Номер телефона заказчика",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("создан", "создан"),
                    ("подтвержден", "подтвержден"),
                    ("выполнен", "выполнен"),
                    ("отменен", "отменен"),
                ],
                default="создан",
                help_text="Статус заказа",
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="parent_category",
            field=models.ForeignKey(
                help_text="Название родительской категории для текущей категории. Может быть пустым",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="shop.productcategory",
                verbose_name="Родительская категория",
            ),
        ),
    ]
