# Generated by Django 5.0.3 on 2024-05-12 19:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_alter_cart_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("1d80b86e-db75-4399-beab-a88c65dd057d"),
                editable=False,
                verbose_name="Идентификатор пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="cart",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="shop.cart",
                verbose_name="Корзина",
            ),
        ),
    ]
